package com.hackingchips.minnou

data class TheGameLevels(val dummy: String = "") {

    /**
     * Definition of the game levels.
     *
     * For every level there is a list of all the chips.
     * For every chip there is a list with parameters for the level:
     *
     *      listOf<Any>(x, y, orientation)
     *
     *      where:
     *          - x and y are the coordinates of the chip inside the
     *            board.
     *            Board coordinates are from 1 to 5 in X direction and
     *            from 1 to 5 in Y direction.
     *            Coordinate 1, 1 is at the top left corner of the board.
     *          - orientation, is the orientation of the chip for the level.
     *
     *      If for a chip, coordinates X and Y are equal to 0 and
     *      orientation is equal to NONE then, that chip is not used in that
     *      level
     */

    val gameLevels = arrayOf(

        // ***** Level 1
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(1, 5, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipE" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipF" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipG" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipH" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(1, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(4, 2, ChipOrientation.VERTICAL),
            "ivChipR" to listOf<Any>(3, 6, ChipOrientation.HORIZONTAL)
        ),
        // ***** Level 2
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(4, 2, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 3, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(3, 5, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(4, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 3
        mapOf("ivChipA" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(2, 5, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(3, 6, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipE" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipF" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipG" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipH" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(4, 3, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 4, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 4
        mapOf("ivChipA" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(6, 5, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipD" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipE" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipF" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipG" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipH" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(4, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(3, 6, ChipOrientation.HORIZONTAL)
        ),
        // ***** Level 5
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipD" to listOf<Any>(1, 5, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(5, 6, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipH" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(1, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipR" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL)
        ),
        // ***** Level 6
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(1, 2, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(1, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipH" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(4, 3, ChipOrientation.VERTICAL),
            "ivChipR" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL)
        ),
        // ***** Level 7
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(4, 2, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipH" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(3, 4, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipP" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 8
        mapOf("ivChipA" to listOf<Any>(4, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(3, 2, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(3, 3, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(4, 3, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(5, 4, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(1, 5, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(3, 5, ChipOrientation.VERTICAL),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(4, 5, ChipOrientation.HORIZONTAL),
            "ivChipQ" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 9
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(4, 2, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(5, 2, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(3, 5, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(6, 5, ChipOrientation.VERTICAL),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(5, 3, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(1, 4, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 10
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(1, 2, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipF" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(5, 6, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(1, 3, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 11
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(1, 2, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(3, 2, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(2, 3, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(5, 6, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(5, 5, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(4, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(3, 3, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(4, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 12
        mapOf("ivChipA" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(5, 2, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(2, 4, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(5, 4, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(1, 5, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(3, 5, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipH" to listOf<Any>(5, 6, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(5, 5, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(6, 5, ChipOrientation.VERTICAL),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(4, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(4, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(2, 6, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 13
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(4, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(1, 2, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(3, 2, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(4, 4, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(2, 6, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(3, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(1, 3, ChipOrientation.VERTICAL),
            "ivChipR" to listOf<Any>(2, 3, ChipOrientation.VERTICAL)
        ),
        // ***** Level 14
        mapOf("ivChipA" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(1, 2, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(1, 3, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(2, 4, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipH" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(4, 5, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(4, 4, ChipOrientation.HORIZONTAL),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(4, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(6, 4, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(2, 6, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 15
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipD" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipE" to listOf<Any>(6, 5, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipG" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipH" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(4, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(3, 6, ChipOrientation.HORIZONTAL)
        ),
        // ***** Level 16
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(2, 2, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(1, 5, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(2, 6, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(4, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(3, 3, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 4, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 17
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(4, 4, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(3, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 2, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 18
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 2, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(1, 4, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(2, 5, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(5, 6, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 19
        mapOf("ivChipA" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(4, 3, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(5, 3, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(2, 5, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(3, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(4, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipQ" to listOf<Any>(6, 4, ChipOrientation.VERTICAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 20
        mapOf("ivChipA" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(1, 2, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(4, 2, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(4, 4, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(2, 6, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(3, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(2, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 21
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(1, 2, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(5, 3, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(2, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(5, 6, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(1, 3, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 22
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(2, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(2, 2, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(3, 3, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(4, 4, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(3, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL)
        ),
        // ***** Level 23
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(2, 2, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(5, 6, ChipOrientation.HORIZONTAL),
            "ivChipX" to listOf<Any>(3, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 2, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipR" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL)
        ),
        // ***** Level 24
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(2, 2, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(4, 4, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(3, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(1 ,6, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(4, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 25
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(5, 3, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(3, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 2, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 26
        mapOf("ivChipA" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(4, 2, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(4, 3, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(5, 3, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(5 ,5, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(5, 6, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(4, 1, ChipOrientation.HORIZONTAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 27
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(3, 2, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(4 ,4, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(1, 5, ChipOrientation.VERTICAL),
            "ivChipJ" to listOf<Any>(4, 5, ChipOrientation.HORIZONTAL),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(6, 4, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(3, 6, ChipOrientation.HORIZONTAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 28
        mapOf("ivChipA" to listOf<Any>(5, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(2, 4, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(3, 5, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(1 ,6, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(5, 6, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(1, 3, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(3, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 29
        mapOf("ivChipA" to listOf<Any>(3, 2, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(1, 4, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(4, 4, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(2, 5, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(6 ,5, ChipOrientation.VERTICAL),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(5, 1, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL)
        ),
        // ***** Level 30
        mapOf("ivChipA" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(1, 2, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(1, 3, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(5, 4, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(1, 5, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(3, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(6 ,5, ChipOrientation.VERTICAL),
            "ivChipI" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(3, 6, ChipOrientation.HORIZONTAL),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(4, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(4, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 31
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(2, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(2, 2, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(5, 3, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(4, 4, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(5 ,5, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(3, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 32
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(3, 3, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(4, 3, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(5, 4, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(6, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(5, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(2, 2, ChipOrientation.HORIZONTAL),
            "ivChipQ" to listOf<Any>(3, 5, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(3, 6, ChipOrientation.HORIZONTAL)
        ),
        // ***** Level 33
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(4, 2, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(5, 2, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(3, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(4, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(1 ,6, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 3, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipQ" to listOf<Any>(6, 4, ChipOrientation.VERTICAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 34
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(2, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(4, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(3, 2, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(1, 4, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(5 ,4, ChipOrientation.VERTICAL),
            "ivChipI" to listOf<Any>(2, 5, ChipOrientation.VERTICAL),
            "ivChipJ" to listOf<Any>(6, 5, ChipOrientation.VERTICAL),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(4, 2, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(4, 3, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(3, 6, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 35
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(4, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(3, 2, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(4, 2, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(4, 4, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(4 ,5, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(2, 6, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 4, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 36
        mapOf("ivChipA" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(5, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(2, 2, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(4, 3, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(5, 4, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(4, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(6 ,5, ChipOrientation.VERTICAL),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(1, 3, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 37
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(4, 2, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(3, 4, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(3, 5, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(4, 5, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(5, 6, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipQ" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipR" to listOf<Any>(6, 3, ChipOrientation.VERTICAL)
        ),
        // ***** Level 38
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(1, 2, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(5, 3, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(1 ,6, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(5, 6, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(1, 3, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 39
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(3, 2, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 2, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(2, 5, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(6 ,5, ChipOrientation.VERTICAL),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(2, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(4, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(3, 6, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 40
        mapOf("ivChipA" to listOf<Any>(5, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(1, 2, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(3, 3, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(4, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(2, 2, ChipOrientation.HORIZONTAL),
            "ivChipQ" to listOf<Any>(4, 4, ChipOrientation.VERTICAL),
            "ivChipR" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL)
        ),
        // ***** Level 41
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(4, 4, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(5 ,5, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(1, 3, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL)
        ),
        // ***** Level 42
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(2, 2, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(4, 3, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(4 ,5, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(6, 5, ChipOrientation.VERTICAL),
            "ivChipJ" to listOf<Any>(2, 6, ChipOrientation.HORIZONTAL),
            "ivChipK" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 43
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(4, 2, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(4, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(2, 6, ChipOrientation.HORIZONTAL),
            "ivChipK" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(6, 4, ChipOrientation.VERTICAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 44
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(1, 4, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(4, 4, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipK" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 4, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 45
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipD" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(4, 4, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(2, 5, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(1, 4, ChipOrientation.VERTICAL),
            "ivChipJ" to listOf<Any>(5, 5, ChipOrientation.VERTICAL),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipP" to listOf<Any>(6, 4, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(3, 1, ChipOrientation.VERTICAL)
        ),
        // ***** Level 46
        mapOf("ivChipA" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(1, 2, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(2, 2, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(4, 4, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(5, 4, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(2, 6, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(4, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(3, 3, ChipOrientation.VERTICAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 47
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(5, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 4, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(1, 5, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(2, 5, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(2, 6, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(4, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(4, 4, ChipOrientation.VERTICAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 48
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(4, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(4, 2, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(4, 4, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(5, 4, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(1, 5, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(2 ,5, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(6, 5, ChipOrientation.VERTICAL),
            "ivChipJ" to listOf<Any>(2, 5, ChipOrientation.HORIZONTAL),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(3, 2, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(2, 6, ChipOrientation.HORIZONTAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 49
        mapOf("ivChipA" to listOf<Any>(3, 2, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(4, 2, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(1, 3, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(4, 4, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(5, 4, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(4, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(3, 6, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 50
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(1, 2, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(3, 5, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(4 ,5, ChipOrientation.VERTICAL),
            "ivChipI" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(4, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 3, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(3, 4, ChipOrientation.HORIZONTAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 51
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(4, 3, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(5, 3, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(1, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(4, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipR" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL)
        ),
        // ***** Level 52
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(3, 2, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(4, 3, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(3, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(4, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(4 ,6, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(6, 4, ChipOrientation.VERTICAL)
        ),
        // ***** Level 53
        mapOf("ivChipA" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(2, 2, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(4, 4, ChipOrientation.HORIZONTAL),
            "ivChipG" to listOf<Any>(3, 5, ChipOrientation.VERTICAL),
            "ivChipH" to listOf<Any>(4 ,5, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipJ" to listOf<Any>(5, 6, ChipOrientation.HORIZONTAL),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(3, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 2, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 54
        mapOf("ivChipA" to listOf<Any>(3, 2, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(4, 4, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(1, 5, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(2, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(4, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(6, 1, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(3, 6, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 55
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(2, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(4, 1, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(4, 4, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(3, 2, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 56
        mapOf("ivChipA" to listOf<Any>(2, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(4, 2, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(5, 2, ChipOrientation.HORIZONTAL),
            "ivChipF" to listOf<Any>(3, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(4, 6, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(5, 3, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(1, 4, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(6, 4, ChipOrientation.VERTICAL)
        ),
        // ***** Level 57
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipC" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(2, 4, ChipOrientation.VERTICAL),
            "ivChipE" to listOf<Any>(1, 5, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(5, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(2 ,6, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(6, 2, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(3, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 58
        mapOf("ivChipA" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipB" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(4, 3, ChipOrientation.VERTICAL),
            "ivChipD" to listOf<Any>(1, 4, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(3, 4, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(2, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(4, 5, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(0 ,0, ChipOrientation.NONE),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(2, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(4, 1, ChipOrientation.HORIZONTAL),
            "ivChipP" to listOf<Any>(6, 4, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(3, 6, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 59
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(5, 2, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(3, 3, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(6, 3, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(4, 4, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(2, 5, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipJ" to listOf<Any>(6, 5, ChipOrientation.VERTICAL),
            "ivChipK" to listOf<Any>(2, 6, ChipOrientation.HORIZONTAL),
            "ivChipX" to listOf<Any>(1, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(1, 4, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipQ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        ),
        // ***** Level 60
        mapOf("ivChipA" to listOf<Any>(1, 1, ChipOrientation.HORIZONTAL),
            "ivChipB" to listOf<Any>(3, 1, ChipOrientation.VERTICAL),
            "ivChipC" to listOf<Any>(5, 1, ChipOrientation.HORIZONTAL),
            "ivChipD" to listOf<Any>(1, 2, ChipOrientation.HORIZONTAL),
            "ivChipE" to listOf<Any>(6, 4, ChipOrientation.VERTICAL),
            "ivChipF" to listOf<Any>(4, 5, ChipOrientation.VERTICAL),
            "ivChipG" to listOf<Any>(1, 6, ChipOrientation.HORIZONTAL),
            "ivChipH" to listOf<Any>(5, 6, ChipOrientation.HORIZONTAL),
            "ivChipI" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipJ" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipK" to listOf<Any>(0, 0, ChipOrientation.NONE),
            "ivChipX" to listOf<Any>(3, 3, ChipOrientation.HORIZONTAL),
            "ivChipO" to listOf<Any>(5, 2, ChipOrientation.VERTICAL),
            "ivChipP" to listOf<Any>(1, 3, ChipOrientation.VERTICAL),
            "ivChipQ" to listOf<Any>(2, 4, ChipOrientation.HORIZONTAL),
            "ivChipR" to listOf<Any>(0, 0, ChipOrientation.NONE)
        )
    )
}
